---
- name: Ensure Boost libraries are installed
  apt: name={{ item }} state=latest
  sudo: yes
  with_items:
    - libboost-dev
    - libboost-graph-dev
    - libboost-date-time-dev
    - libboost-system-dev
    - libboost-filesystem-dev
    - libboost-program-options-dev
  when: ansible_os_family == "Debian"

- name: Ensure Boost libraries are installed
  homebrew: name=boost state=latest install_options=c++11
  when: ansible_os_family == "Darwin"
