---
- name: Install Python Dev 
  apt: pkg=python-dev state=latest
  sudo: yes
  when: ansible_os_family == "Debian"

- name: Install Python PIP 
  apt: pkg=python-pip state=latest
  sudo: yes
  when: ansible_os_family == "Debian"

- name: Make sure VirtualEnv is available
  pip: name=virtualenv
  sudo: yes
