---
- name: Install PostgreSQL 
  apt: pkg=postgresql state=latest
  when: ansible_os_family == "Debian"
- name: Install PostgreSQL user
  sudo: yes
  sudo_user: postgres
  postgresql_user: name=fuzzed password=fuzzed role_attr_flags=NOSUPERUSER
  when: ansible_os_family == "Debian"
- name: Install PostgreSQL database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name=fuzzed owner=fuzzed
  when: ansible_os_family == "Debian"



