---
- name: Ensure C++ XML support is installed
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - libxerces-c-dev
    - xsdcxx
  when: ansible_os_family == "Debian"

- name: Ensure C++ XML support is installed
  homebrew: name=xerces-c state=present
  when: ansible_os_family == "Darwin"


