---
- name: Ensure Django is installed
  pip: name=django version=1.8.18

- name: Ensure Django Social Auth is installed
  pip: name=python-social-auth version=0.2.21

- name: Ensure Django SocialAuth dependencies are installed
  pip: name={{item}} 
  with_items:
  - python-openid
  - python-oauth2

- name: Ensure Django Require is installed
  pip: name=django-require

- name: Ensure Django Robots is installed
  pip: name=django-robots

- name: Ensure Django Tastypie is installed
  pip: name=git+git://github.com/django-tastypie/django-tastypie.git@256ebe1de9a78dfb5d4d6e938b813cf4c5c4ac1b

- name: Ensure Django configurations is installed
  pip: name=django-configurations

