---
- name: Ensure Django is installed
  become: yes
  pip: name=django version=2.0.3 executable=pip3

- name: Ensure Django Social Auth is installed
  become: yes
  pip: name=social-auth-app-django executable=pip3

- name: Ensure Django Require is installed
  become: yes
  pip: name=django-require executable=pip3

- name: Ensure Django Robots is installed
  become: yes
  pip: name=django-robots executable=pip3

# URL not possible with older Ansible pip module, see https://github.com/ansible/ansible-modules-core/issues/226
- name: Ensure Django Tastypie is installed
  become: yes
  command: pip3 install git+git://github.com/django-tastypie/django-tastypie.git@256ebe1de9a78dfb5d4d6e938b813cf4c5c4ac1b

- name: Ensure Django configurations is installed
  become: yes
  pip: name=django-configurations executable=pip3

