---
- name: Ensure apache and modules are at the latest version
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
  - apache2
  - libapache2-mod-wsgi 
  when: ansible_os_family == "Debian"

- name: Ensure apache2 is running
  service: name=apache2 state=started
  when: ansible_os_family == "Debian"