---
- name: Ensure Django is installed
  sudo: yes
  easy_install: name=django
- name: Ensure Django SocialAuth is installed
  sudo: yes
  easy_install: name=django-socialauth
- name: Ensure Django Require is installed
  sudo: yes
  easy_install: name=django-require 
- name: Ensure Django Tastypie is installed
  sudo: yes
  easy_install: name=django-tastypie 
- name: Ensure Django Wiki and dependencies are installed
  sudo: yes
  easy_install: name={{item}}
  with_items:
  - djiki
  - py-wikimarkup
  - defusedxml
- name: Ensure Django configurations is installed
  sudo: yes
  easy_install: name=django-configurations
- name: Ensure OAuth client libary is installed for testing purposes
  sudo: yes
  easy_install: name=requests_oauthlib 
