---
- name: Configure production web servers
  hosts: webservers
  user: root
  environment: env_vars # needed for making ./manage.py workable, comes from host config

  vars_prompt:
    - name: "release_version"
      prompt: "FuzzEd release version"
      private: no
      default: "0.7.1"

  roles:
    - all
    - run_fuzzed_fe
    - deployed_fuzzed_fe_wsgi

- name: Configure production backend servers
  hosts: backendservers
  user: root

  vars_prompt:
    - name: "release_version"
      prompt: "FuzzEd backend release version"
      private: no
      default: "0.7.1"

  roles:
    - all
    - run_fuzzed_be
    - deployed_fuzzed_be_daemon
