---
- name: Upload FuzzEd Backend release to server
  copy: src=../dist/FuzzEdBackend-{{release_version}}.tar.gz dest={{ be_install_base_dir }}/

- name: Create target directory for unarchiving backend
  file: path={{ be_install_base_dir }}/{{ release_version }}/ state=directory

- name: Unarchive backend release package on server
  unarchive: copy=no src={{ be_install_base_dir }}/FuzzEdBackend-{{release_version}}.tar.gz dest={{ be_install_base_dir }}/{{ release_version }}/

- name: Adjusting links for pointing to download package
  file: src={{ be_install_base_dir }}/{{ release_version }}/ dest={{ be_base_dir }} state=link force=yes

- name: Ensure access rights for startup script
  file: path={{ be_base_dir }}/backends/initscript.sh state=touch mode="u+x"

- name: Ensure startup script link
  file: src={{ be_base_dir }}/backends/initscript.sh dest=/etc/init.d/fuzzed-backend owner=root group=root force=yes state=link

- name: Ensure FuzzEd backend being started
  service: name=fuzzed-backend state=started

